from .analise import analisar_comando_gemini
from .clima import obter_coordenadas, obter_previsao_futuro, obter_previsao_tempo, obter_data_hora_atual
from .musica import pesquisar_musica_youtube
from .gerenciar_agenda import GerenciadorAgenda
from .controlador_navegador import ControladorNavegador
from .tradutor_clipboard import TradutorClipboard, iniciar_monitoramento
from .controle_volume_updated import ControladorVolume